[project]
name = "haxor-news"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "prompt-toolkit>=3.0.48",
    "pygments>=2.18.0",
    "requests>=2.32.3",
]
